global-business-support/evalvue-mobile

- App.tsx
- Components/Forms/EmpForm.jsx
- Components/Forms/OrgRegistration.jsx
- Components/Forms/PostReview.jsx
- Components/Styles/customStyle.js
- package-lock.json
> employee, post form added

- Components/Pages/EmployeeList.jsx
- Components/Pages/SearchByAadhar.jsx
- Components/Styles/customStyle.js
- Components/Styles/listStyle.js
emp list, search by aadhar  added
> emp list, search by aadhar  added

- App.jsx
- Components/Forms/OrgRegistration.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Pages/Feed.jsx
- Components/Pages/Notifications.jsx
- Components/Pages/OrgList.jsx
- Components/Payment-Pages/PaymentHistory.jsx
- Components/Payment-Pages/Subscription.jsx
- Components/ReviewCards/ReviewCards.jsx
- Components/Styles/listStyle.js
- Components/Styles/paymentStyle.js
- Drawer/AppTabs.jsx
- package-lock.json
- package.json
paymentHistory, subscriptionHistory pages added by keshav
> paymentHistory, subscriptionHistory pages added by keshav

- App.jsx
- Components/Styles/customStyle.js
- Drawer/AppDrawer.jsx
- Drawer/DrawerContent.jsx
> Drawer added

- App.jsx
- AppStack.tsx
- Components/Authentication/Login.jsx
- Components/CustomModal/CustomModal.jsx
- OnboardingScreens/slides/Slide3.jsx
> update login api

- Components/Forms/UserRegistration.jsx
- Drawer/AppDrawer.jsx
- Validation/Validation.js
user register validation updated
> user register validation updated

- AppStack.tsx
- Components/Context/ContextFile.js
- Components/Forms/UserRegistration.jsx
- Components/Pages/Feed.jsx
- Components/ReviewCards/ReviewCards.jsx
> register user api added

- API-Management/ApiBackendRequest.js
- Components/Authentication/ForgotPassword.jsx
- Components/Authentication/Login.jsx
- Components/Authentication/OtpPassword.jsx
- Components/CustomModal/CustomModal.jsx
- Components/Styles/customStyle.js
otp and login functionality added by keshav.
> otp and login functionality added by keshav.

- Components/Pages/EmployeeList.jsx
- Components/Pages/OrgList.jsx
- Components/Styles/listStyle.js
> employee list update

- Components/Authentication/ForgotPassword.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/ShimmerUI/ShimmerUI.jsx
- Components/Styles/empListStyle.js
employee details page functionality added by keshav.
> employee details page functionality added by keshav.

- Components/Forms/OrgRegistration.jsx
- android/app/build.gradle
- android/settings.gradle
- package-lock.json
- package.json
add organization image upload functionality added
> add organization image upload functionality added

- Components/Forms/OrgRegistration.jsx
- Components/Styles/customStyle.js
> add organization api added

- Components/Pages/EmployeeList.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/ThreeDotMenu .jsx
> making threedotmenu

- .vscode/launch.json
- Components/CustomModal/CustomModal.jsx
- Components/Forms/EmpForm.jsx
- Components/Forms/OrgRegistration.jsx
- Components/Forms/PostReview.jsx
add organization and add employee api added
> add organization and add employee api added

- App.jsx
- AppStack.tsx
- Components/CustomModal/NetworkErrorOverlay.js
- Components/Pages/EmployeeList.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/ThreeDotMenu .jsx
- Utils/Storage.js
- package-lock.json
- package.json
> create network ,storage file

- Components/Forms/PostReview.jsx
- Components/Othercomponent/TruncatedText.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/SearchByAadhar.jsx
- Components/PdfRender/PdfRender.jsx
- Components/Styles/listStyle.js
- Drawer/AppDrawer.jsx
> post review api added

- Components/Forms/EmpForm.jsx
- Components/Forms/PostReview.jsx
- Components/Othercomponent/TruncatedText.jsx
- Components/Pages/AddToOrganization.jsx
- Components/Pages/EmpInfo.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Pages/SearchByAadhar.jsx
- Components/Pages/ThreeDotMenu .jsx
- Drawer/AppDrawer.jsx
- Drawer/AppTabs.jsx
terminate and add terminated employee functionality added
> terminate and add terminated employee functionality added

- android/app/src/main/AndroidManifest.xml
- package-lock.json
> resolve previous commit

- API-Management/mmkv-Storage.js
- Components/Forms/EmpForm.jsx
- Components/Forms/OrgRegistration.jsx
- Components/Othercomponent/TruncatedText.jsx
- Components/Pages/AddToOrganization.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/SearchByAadhar.jsx
- Components/Pages/ThreeDotMenu .jsx
- Drawer/AppDrawer.jsx
- Drawer/AppTabs.jsx
> update last 4 day code

- Components/Forms/EmpForm.jsx
- Components/Othercomponent/TruncatedText.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Payment-Pages/PaymentHistory.jsx
- Components/Payment-Pages/Subscription.jsx
- Components/ShimmerUI/EmpReviewShimmerUI.jsx
- Components/ShimmerUI/ListShimmerUI.jsx
- Components/ShimmerUI/PaymentShimmerUI.jsx
- Components/ShimmerUI/ReviewShimmerUI.jsx
- Components/ShimmerUI/ShimmerText.jsx
- Components/ShimmerUI/useShimmerAnimation.jsx
edit employee functionality added, shimmer UI modified by Keshav.
> edit employee functionality added, shimmer UI modified by Keshav.

- API-Management/ApiBackendRequest.js
- API-Management/ApiInterceptor.js
- API-Management/mmkv-Storage.js
- API-Management/navigationService.js
- App.jsx
- AppStack.tsx
- Components/Authentication/Login.jsx
- Components/Othercomponent/OfferPosters.js
- Components/Pages/Feed.jsx
- Drawer/AppTabs.jsx
- Utils/Storage.js
access token resolve, Add Poster one feed
> access token resolve, Add Poster one feed

- Components/Custom-Functions/customFunctions.jsx
- Components/Pages/EmployeeDetails.jsx
- Components/Pages/EmployeeList.jsx
- Components/Pages/Feed.jsx
- Components/Pages/Notifications.jsx
- Components/Pages/OrgList.jsx
- Components/Payment-Pages/PaymentHistory.jsx
- Components/Payment-Pages/Subscription.jsx
- Components/ReviewCards/ReviewCards.jsx
- Components/ShimmerUI/ReviewShimmerUI.jsx
- Components/Styles/empListStyle.js
- Components/Styles/listStyle.js
- Drawer/AppTabs.jsx
> feed UI modified

- Components/Pages/OrgList.jsx
- Drawer/AppTabs.jsx
- package-lock.json
- package.json
> Create payment method

- Components/Forms/OrgRegistration.jsx
- Components/Receipt/Receipt.jsx
org registration picker item update
> org registration picker item update

- Components/CustomModal/NetworkErrorOverlay.js
- Components/Pages/Help.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/Plan.jsx
- Drawer/AppDrawer.jsx
- Drawer/DrawerContent.jsx
- package-lock.json
- package.json
help, subscription plan page added.
> help, subscription plan page added.

- Components/Authentication/OtpPassword.jsx
- Components/Forms/OrgRegistration.jsx
- Components/Forms/PostReview.jsx
- Components/Pages/AboutUs.jsx
edited about us component, image preview added in post review component
> edited about us component, image preview added in post review component

- API-Management/ApiBackendRequest.js
- API-Management/ApiInterceptor.js
- API-Management/mmkv-Storage.js
- API-Management/navigationService.js
- API-Management/tokenUtils.js
- Components/Authentication/Login.jsx
- Components/Forms/UserRegistration.jsx
- Components/Pages/Notifications.jsx
- Components/Pages/OrgList.jsx
- Components/Pages/Plan.jsx
- Drawer/DrawerContent.jsx
- package-lock.json
- package.json
access token expiry handled by Keshav.
> access token expiry handled by Keshav.

- Components/Pages/EmployeeList.jsx
employeeList error resolved by Keshav.
> employeeList error resolved by Keshav.

- API-Management/mmkv-Storage.js
- App.jsx
- AppStack.tsx
- Drawer/DrawerContent.jsx
- OnboardingScreens/Onboarding.jsx
- OnboardingScreens/slides/Slide3.jsx
> fixed onboarding screens
